export const generateReport = (data) => {
  // Generate a printable HTML window
  const printWindow = window.open("", "_blank");

  if (!printWindow) {
    alert("Please allow popups to generate the report.");
    return;
  }

  const { hardwareCost, powerKwh, clusters, pue } = data;
  const totalRacks = clusters?.reduce((acc, c) => acc + c.rackCount, 0) || 0;
  const monthlyOpEx = powerKwh * 0.12 * pue;
  const yearlyTCO = hardwareCost / 3 + monthlyOpEx * 12; // Simple 3y amort

  const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>CloudSmart Executive Briefing</title>
            <style>
                body { font-family: 'Inter', sans-serif; color: #1e293b; max-width: 800px; mx-auto; padding: 40px; }
                h1 { color: #0f172a; border-bottom: 2px solid #2dd4bf; padding-bottom: 10px; }
                h2 { color: #334155; margin-top: 30px; }
                .metric-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-top: 20px; }
                .metric-card { background: #f8fafc; padding: 20px; border-radius: 8px; border: 1px solid #e2e8f0; }
                .label { font-size: 0.875rem; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; }
                .value { font-size: 1.5rem; font-weight: bold; color: #0f172a; margin-top: 5px; }
                .cluster-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
                .cluster-table th { text-align: left; border-bottom: 2px solid #e2e8f0; padding: 10px; font-size: 0.875rem; color: #64748b; }
                .cluster-table td { padding: 10px; border-bottom: 1px solid #e2e8f0; }
                .footer { margin-top: 50px; text-align: center; color: #94a3b8; font-size: 0.75rem; border-top: 1px solid #e2e8f0; padding-top: 20px; }
                .highlight { color: #0f766e; }
            </style>
        </head>
        <body>
            <h1>CloudSmart <span style="font-weight: 300;">FinOps Strategy</span></h1>
            <p>Generated on ${new Date().toLocaleDateString()}</p>

            <h2>Executive Summary</h2>
            <div class="metric-grid">
                <div class="metric-card">
                    <div class="label">Total CapEx Investment</div>
                    <div class="value">$${hardwareCost.toLocaleString()}</div>
                </div>
                 <div class="metric-card">
                    <div class="label">Annual Projected TCO</div>
                    <div class="value highlight">$${Math.round(yearlyTCO).toLocaleString()}</div>
                </div>
                <div class="metric-card">
                    <div class="label">Infrastructure Efficiency (PUE)</div>
                    <div class="value">${pue}</div>
                </div>
                <div class="metric-card">
                    <div class="label">Total Racks Deployed</div>
                    <div class="value">${totalRacks}</div>
                </div>
            </div>

            <h2>Cluster Topology</h2>
            <table class="cluster-table">
                <thead>
                    <tr>
                        <th>Cluster Name</th>
                        <th>Type</th>
                        <th>Racks</th>
                        <th>Power Load (kW)</th>
                    </tr>
                </thead>
                <tbody>
                    ${clusters
                      ?.map(
                        (c) => `
                        <tr>
                            <td>${c.name}</td>
                            <td>${c.type.toUpperCase()}</td>
                            <td>${c.rackCount}</td>
                            <td>${(c.rackCount * c.powerKwPerRack).toLocaleString()} kW</td>
                        </tr>
                    `,
                      )
                      .join("")}
                </tbody>
            </table>

            <h2>Strategic Recommendation</h2>
            <p style="line-height: 1.6; margin-top: 20px;">
                Based on the current <strong>${pue} PUE</strong> baseline, this infrastructure is operating 
                ${pue < 1.4 ? "efficiently" : "inefficiently"} compared to industry standards. 
                Migration of <strong>${clusters?.find((c) => c.type === "ai")?.name || "legacy workloads"}</strong> 
                to public cloud Spot Instances could reduce TCO by an estimated <strong>15-20%</strong>.
            </p>

            <div class="footer">
                Generated by CloudSmart v2.0 Enterprise Engine
            </div>

            <script>
                window.onload = () => window.print();
            </script>
        </body>
        </html>
    `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
};
